
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const FILTER_CUSTOMERS = 'FILTER_CUSTOMERS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERT = 'SET_ALERT';

export const GET_ACCOUNT = 'GET_ACCOUNT';
export const ACCOUNTOWNERS_ERROR = 'ACCOUNTOWNERS_ERROR'

export const GET_BENEFICIARIES = 'GET_BENEFICIARIES';
export const BENEFICIARIES_ERROR = 'BENEFICIARIES_ERROR'

export const ADD_BENEFICIARY = 'ADD_BENEFICIARY';
export const BENEFICIARY_ERROR = 'BENEFICIARY_ERROR'

export const UPDATE_BENEFICIARIES = 'UPDATE_BENEFICIARIES';
export const UPDATE_BENEFICIARIES_ERROR = 'UPDATE_BENEFICIARIES_ERROR'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'

export const GET_BENEFICIARY = 'GET_BENEFICIARY';
// export const BENEFICIARY_ERROR = 'BENEFICIARY_ERROR'
export const USER_ERROR = 'USER_ERROR';